// <auto-generated />
using System;
using GUID.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace guid.Migrations
{
    [DbContext(typeof(GUIDContext))]
    [Migration("20190205165957_GUIDMigration")]
    partial class GUIDMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("GUID.Models.GUIDData", b =>
                {
                    b.Property<string>("guid")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("expire");

                    b.Property<string>("user");

                    b.HasKey("guid");

                    b.ToTable("GUIDs");
                });
#pragma warning restore 612, 618
        }
    }
}
